name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy Backend
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu/apps/sales-tracker/sales-tracker-backend/
          git pull
          npm install
          # Set environment variables in the backend application
          export DB_USERNAME=${{ secrets.DB_USERNAME }}
          export DB_NAME=${{ secrets.DB_NAME }}
          export DB_PORT=${{ secrets.DB_PORT }}
          export DB_PIN=${{ secrets.PORT }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          pm2 restart salestracker-backend || pm2 start index.js --name salestracker-backend
